drop
database if exists verificacao_servicos;
create
database verificacao_servicos;
use
verificacao_servicos;

CREATE TABLE TIPOCARGO
(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO     VARCHAR(255)
);

CREATE TABLE TIPOUSUARIO
(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO     VARCHAR(255)
);

CREATE TABLE ATIVIDADE
(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO     VARCHAR(255),
    IDTIPOCARGO   INT,
    FOREIGN KEY (IDTIPOCARGO) REFERENCES TIPOCARGO (ID)
);

CREATE TABLE FUNCIONARIO
(
    ID            INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME          VARCHAR(255),
    CPF           VARCHAR(11) UNIQUE,
    TELEFONE      VARCHAR(11),
    DTNASCIMENTO  DATE,
    CTPS          VARCHAR(11) UNIQUE,
    IDTIPOCARGO   INT,
    MATRICULA 	  NUMERIC(6) UNIQUE,
    SENHA 		  VARCHAR(55),
    FOREIGN KEY (IDTIPOCARGO) REFERENCES TIPOCARGO (ID),
    IDTIPOUSUARIO INT,
    FOREIGN KEY (IDTIPOUSUARIO) REFERENCES TIPOUSUARIO (ID)
);

CREATE TABLE ENDERECO
(
    ID     INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    RUA    VARCHAR(55),
    NUMERO VARCHAR(55),
    BAIRRO VARCHAR(55),
    CEP    VARCHAR(8),
    CIDADE VARCHAR(55),
    ESTADO VARCHAR(2)
);

CREATE TABLE SALA
(
    ID         INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NUMERO     VARCHAR(10),
    DISPONIVEL BOOLEAN
);

CREATE TABLE PRESTACAO
(
    ID            INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IDFUNCIONARIO INT,
    FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO (ID),
    IDSALA        INT,
    FOREIGN KEY (IDSALA) REFERENCES SALA (ID),
    DATAINICIO    DATETIME,
    DATAFIM       DATETIME
);

CREATE TABLE PRESTACAO_ATIVIDADE
(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IDATIVIDADE INT NOT NULL,
    FOREIGN KEY (IDATIVIDADE) REFERENCES ATIVIDADE (ID),
    IDPRESTACAO INT NOT NULL,
    FOREIGN KEY (IDPRESTACAO) REFERENCES PRESTACAO (ID)
);

INSERT INTO TIPOUSUARIO (descricao)
VALUES ('ADMINISTRADOR');
INSERT INTO TIPOUSUARIO (descricao)
VALUES ('FUNCIONARIO');

INSERT INTO TIPOCARGO (descricao)
VALUES ('FAXINA');
INSERT INTO TIPOCARGO (descricao)
VALUES ('ZELADORIA');
INSERT INTO TIPOCARGO (descricao)
VALUES ('TECNICO TI');

INSERT INTO SALA (numero, disponivel)
VALUES (101, TRUE);
INSERT INTO SALA (numero, disponivel)
VALUES (102, TRUE);
INSERT INTO SALA (numero, disponivel)
VALUES (103, TRUE);
INSERT INTO SALA (numero, disponivel)
VALUES (201, TRUE);
INSERT INTO SALA (numero, disponivel)
VALUES (202, TRUE);